App\Entity\Lesson:
    attributes:
        id:
            groups: ['list', 'lesson_details', 'course_modules']
        title:
            groups: ['list', 'lesson_details', 'course_modules']
        description:
            groups: ['lesson_details']
        embedType:
            groups: ['lesson_details']
        embedCode:
            groups: ['lesson_details']
        module:
            groups: ['lesson_details']
        position:
            groups: ['list', 'lesson_details']
        created:
            groups: ['lesson_details']
        updated:
            groups: ['lesson_details']
        coverImageName:
            groups: ['list', 'lesson_details', 'course_modules']
        durationInMinutes:
            groups: ['list', 'lesson_details', 'course_modules']
        attachments:
            groups: ['lesson_details']
        blocked:
            groups: ['list', 'lesson_details', 'course_modules']
